import React, { useEffect, useState, useCallback } from 'react';
import { Button } from '@troott/ui/button';
import { Badge } from '@troott/ui/badge';
import { Label } from '@troott/ui/label';
import {
    FileAudio,
    Clock,
    Globe,
    Lock,
    User,
    Tag,
    Calendar,
    Pencil,
    Trash2,
    Copy,
    ChevronUp,
    Link as LinkIcon,
    CheckCircle2,
    ArrowUp,
} from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import storage from '@/api/services/local-storage';
import {
    PATH_GET_STARTED,
    PATH_SEG_SERMONS,
    PATH_STUDIO_PREFIX,
} from '@/routes/paths';
import { studioSermonsListPath } from '@/routes/paths';
import { useQueryClient } from '@tanstack/react-query';
import { visibilityToIsPublic } from '@/utils/sermon-visibility.util';
import { isApiHttp2xxErrorEnvelope } from '@/api/core/api-envelope-toast';
import { toast } from 'sonner';
import { useUpload, uploadActions } from '@/context/upload/uploadState';
import { useDraft } from '@/context/draft/draftState';
import { sermonQueryKeys } from '@/constants/sermon-query-keys';
import useContextType from '@/hooks/shared/useContextType';
import { useCreator } from '@/context/creator/useCreator';
import { useMinister } from '@/context/minister/useMinister';
import { resolveStudioSermonOwnerId } from '@/utils/studio-sermon-owner.util';
import { usePublishSermonMutation } from '@/hooks/app/useSermon';
import type { PublishSermonDTO } from '@/dtos/sermon.dto';
import { MediaStatus } from '@/dtos/sermon-media.types';

interface ReviewSubmitProps {
    onModalClose?: () => void;
    onSubmitRef?: React.MutableRefObject<(() => void) | null>;
    onSaveDraftRef?: React.MutableRefObject<(() => Promise<void>) | null>;
    /** When false, only registers footer handlers (save/publish) for modal close. */
    showPanel?: boolean;
}

function apiErrorMessage(err: unknown): string {
    if (
        err &&
        typeof err === 'object' &&
        'message' in err &&
        typeof (err as { message: unknown }).message === 'string'
    ) {
        return (err as { message: string }).message;
    }
    return 'Something went wrong. Please try again.';
}

const ReviewSubmit: React.FC<ReviewSubmitProps> = ({
    onModalClose,
    onSubmitRef,
    onSaveDraftRef,
    showPanel = true,
}) => {
    const { state, dispatch } = useUpload();
    const { updateDraft } = useDraft();
    const { uploadData, isLoading, uploadComplete, progress } = state;
    const navigate = useNavigate();
    const queryClient = useQueryClient();
    const { userContext } = useContextType();
    const { minister } = useMinister();
    const { creatorId } = useCreator();
    const user = userContext.user as Record<string, unknown> | null;
    const ministerId = resolveStudioSermonOwnerId(
        user,
        minister?.id,
        creatorId,
    );
    const publishSermonMutation = usePublishSermonMutation();
    const [showMoreFields, setShowMoreFields] = useState(false);
    const [linkCopied, setLinkCopied] = useState(false);
    const [isThumbnailAutoGenerated] = useState(true); // You can make this dynamic based on your logic
    const [autoSaveDone, setAutoSaveDone] = useState(false);

    // Check if upload is in progress
    const isUploading =
        uploadData.file &&
        !uploadComplete &&
        isLoading &&
        progress > 0 &&
        progress < 100;

    const formatFileSize = (bytes: number): string => {
        if (bytes === 0) return '0 Bytes';
        const k = 1024;
        const sizes = ['Bytes', 'KB', 'MB', 'GB'];
        const i = Math.floor(Math.log(bytes) / Math.log(k));
        return parseFloat((bytes / Math.pow(k, i)).toFixed(2)) + ' ' + sizes[i];
    };

    // Auto-save metadata to the server when audio upload completes (silent).
    const handleAutoSaveDraft = useCallback(async () => {
        const sermonId = uploadData.sermonId ?? uploadData.draftId;
        if (!sermonId) return;
        try {
            await updateDraft(sermonId, {
                title: uploadData.title,
                description: uploadData.description,
                tags: uploadData.tags,
                category: uploadData.category,
                isPublic: uploadData.isPublic,
                scheduledDate: uploadData.scheduledDate,
                seriesId: uploadData.seriesId,
            });
            if (!uploadData.draftId) {
                dispatch(
                    uploadActions.setUploadData({ draftId: sermonId }),
                );
            }
            void queryClient.invalidateQueries({
                queryKey: sermonQueryKeys.all,
            });
            if (ministerId) {
                void queryClient.invalidateQueries({
                    queryKey: sermonQueryKeys.ministerListRoot(ministerId),
                });
            }
        } catch (error: unknown) {
            console.error('Auto-save draft failed:', error);
        }
    }, [uploadData, updateDraft, dispatch, queryClient, ministerId]);

    const buildPublishBody = useCallback(
        (publishStatus: 'published' | 'draft') => {
            const userId = storage.getUserID();
            const release = uploadData.scheduledDate ?? new Date();
            const audioRef =
                uploadData.uploadRef?.trim() ||
                uploadData.sermonId?.trim() ||
                '';

            return {
                title: uploadData.title,
                description: uploadData.description,
                topic: uploadData.category || '',
                tags: uploadData.tags ?? [],
                visibility:
                    uploadData.visibility ??
                    (uploadData.isPublic === false ? 'private' : 'public'),
                isPublic: visibilityToIsPublic(
                    uploadData.visibility ??
                        (uploadData.isPublic === false
                            ? 'private'
                            : 'public'),
                ),
                minister: ministerId || userId,
                publishedBy: userId,
                sermon: audioRef,
                size: uploadData.file?.size ?? 0,
                duration: 0,
                preachedAt: release.toISOString(),
                preachedYear: String(release.getFullYear()),
                isSeries: false,
                status:
                    publishStatus === 'published'
                        ? MediaStatus.PUBLISHED
                        : MediaStatus.DRAFT,
                isPublished: publishStatus === 'published',
            } as Record<string, unknown>;
        },
        [ministerId, uploadData],
    );

    const handleSaveDraft = useCallback(async () => {
        dispatch(uploadActions.setLoading(true));
        try {
            if (uploadData.sermonId) {
                const res = await publishSermonMutation.mutateAsync({
                    id: uploadData.sermonId,
                    payload:
                        buildPublishBody('draft') as unknown as PublishSermonDTO,
                });
                if (res.error) {
                    if (!isApiHttp2xxErrorEnvelope(res)) {
                        toast.error(res.message || 'Could not save draft.');
                    }
                    return;
                }
                await queryClient.invalidateQueries({
                    queryKey: sermonQueryKeys.all,
                });
                if (ministerId) {
                    await queryClient.invalidateQueries({
                        queryKey: sermonQueryKeys.ministerListRoot(ministerId),
                    });
                }
                toast.success('Draft saved', {
                    description:
                        'Sermon metadata has been saved on the server.',
                });
                dispatch(uploadActions.resetUpload());
                onModalClose?.();
                const code = storage.getStudioCode()?.trim();
                navigate(code ? studioSermonsListPath(code) : PATH_GET_STARTED);
                return;
            }

            if (uploadData.draftId) {
                await updateDraft(uploadData.draftId, {
                    title: uploadData.title,
                    description: uploadData.description,
                    tags: uploadData.tags,
                    category: uploadData.category,
                    visibility:
                        uploadData.visibility ??
                        (uploadData.isPublic === false ? 'private' : 'public'),
                    isPublic: visibilityToIsPublic(
                        uploadData.visibility ??
                            (uploadData.isPublic === false
                                ? 'private'
                                : 'public'),
                    ),
                    scheduledDate: uploadData.scheduledDate,
                    seriesId: uploadData.seriesId,
                });
                await queryClient.invalidateQueries({
                    queryKey: sermonQueryKeys.all,
                });
                if (ministerId) {
                    await queryClient.invalidateQueries({
                        queryKey: sermonQueryKeys.ministerListRoot(ministerId),
                    });
                }
                toast.success('Draft updated', {
                    description: 'Your sermon draft has been saved.',
                });
            } else {
                toast.error('Upload audio first', {
                    description:
                        'Finish the audio upload step before saving a draft.',
                });
                return;
            }
            onModalClose?.();
            const code = storage.getStudioCode()?.trim();
            navigate(code ? studioSermonsListPath(code) : PATH_GET_STARTED);
        } catch (error: unknown) {
            toast.error('Failed to save draft', {
                description: apiErrorMessage(error),
            });
        } finally {
            dispatch(uploadActions.setLoading(false));
        }
    }, [
        uploadData,
        updateDraft,
        dispatch,
        onModalClose,
        navigate,
        buildPublishBody,
        queryClient,
        ministerId,
        publishSermonMutation,
    ]);

    const handleSubmit = useCallback(async () => {
        if (!uploadComplete) {
            await handleSaveDraft();
            return;
        }

        const sermonId = uploadData.sermonId;
        if (!sermonId) {
            toast.error('Upload is not complete. Finish audio upload first.');
            return;
        }

        if (uploadData.coverUploadStatus !== 'uploaded') {
            toast.error('Add and save a cover on Details', {
                description:
                    'Upload a thumbnail on the Details step before publishing.',
            });
            dispatch(uploadActions.setStep('details'));
            return;
        }

        dispatch(uploadActions.setLoading(true));
        try {
            const res = await publishSermonMutation.mutateAsync({
                id: sermonId,
                payload:
                    buildPublishBody('published') as unknown as PublishSermonDTO,
            });
            if (res.error) {
                if (!isApiHttp2xxErrorEnvelope(res)) {
                    toast.error(res.message || 'Could not publish.');
                }
                return;
            }
            await queryClient.invalidateQueries({
                queryKey: sermonQueryKeys.all,
            });
            if (ministerId) {
                await queryClient.invalidateQueries({
                    queryKey: sermonQueryKeys.ministerListRoot(ministerId),
                });
            }
            dispatch(uploadActions.resetUpload());
            onModalClose?.();
            const code = storage.getStudioCode()?.trim();
            navigate(code ? studioSermonsListPath(code) : PATH_GET_STARTED);
            toast.success('Sermon published successfully', {
                description: 'Your sermon metadata has been saved.',
            });
        } catch (e: unknown) {
            toast.error(apiErrorMessage(e));
        } finally {
            dispatch(uploadActions.setLoading(false));
        }
    }, [
        dispatch,
        uploadData.sermonId,
        uploadData.coverUploadStatus,
        uploadComplete,
        buildPublishBody,
        onModalClose,
        navigate,
        queryClient,
        handleSaveDraft,
        ministerId,
        publishSermonMutation,
    ]);

    // Expose submit handler to parent component
    useEffect(() => {
        if (onSubmitRef) {
            onSubmitRef.current = () => {
                void handleSubmit();
            };
        }
        return () => {
            if (onSubmitRef) {
                onSubmitRef.current = null;
            }
        };
    }, [onSubmitRef, handleSubmit]);

    // Expose save draft handler to parent component
    useEffect(() => {
        if (onSaveDraftRef) {
            onSaveDraftRef.current = handleSaveDraft;
        }
        return () => {
            if (onSaveDraftRef) {
                onSaveDraftRef.current = null;
            }
        };
    }, [onSaveDraftRef, handleSaveDraft]);

    // Clear any previous loading states when component mounts
    useEffect(() => {
        dispatch(uploadActions.setLoading(false));
    }, [dispatch]);

    // Auto-save to draft when upload completes (silent, no navigation)
    useEffect(() => {
        if (
            uploadComplete &&
            uploadData.sermonId &&
            !autoSaveDone &&
            uploadData.title &&
            uploadData.description
        ) {
            setAutoSaveDone(true);
            void handleAutoSaveDraft();
        }
    }, [
        uploadComplete,
        autoSaveDone,
        handleAutoSaveDraft,
        uploadData.sermonId,
        uploadData.title,
        uploadData.description,
    ]);

    const generateSermonLink = () => {
        if (uploadComplete && uploadData.sermonId) {
            return `https://troott.be/${uploadData.sermonId}`;
        }
        // Generate a random link for preview
        return `https://troott.be/dcXlvoEauNU`;
    };

    const handleCopyLink = async () => {
        const link = generateSermonLink();
        if (link) {
            try {
                await navigator.clipboard.writeText(link);
                setLinkCopied(true);
                setTimeout(() => setLinkCopied(false), 2000);
            } catch (err) {
                console.error('Failed to copy link:', err);
            }
        }
    };

    const handleEditFile = () => {
        dispatch(uploadActions.setStep('progress'));
    };

    const handleDeleteFile = () => {
        dispatch(uploadActions.setFile(null));
        dispatch(uploadActions.setProgress(0));
        dispatch(uploadActions.setUploadComplete(false));
    };

    const handleEditTitle = () => {
        dispatch(uploadActions.setStep('details'));
    };

    const handleEditDescription = () => {
        dispatch(uploadActions.setStep('details'));
    };

    const handleEditThumbnail = () => {
        dispatch(uploadActions.setStep('details'));
    };

    if (!showPanel) {
        return null;
    }

    return (
        <div className="grid h-full min-h-0 grid-cols-1 gap-4 lg:grid-cols-[1.5fr_1fr]">
            {/* Left Column - Content Details */}
            <div className="max-h-full min-h-0 space-y-4 overflow-y-auto pr-2 scrollbar-none">
                {/* File Information */}
                {uploadData.file && (
                    <div className="border border-border/50 rounded-lg p-4">
                        <div className="flex items-center justify-between">
                            <div className="flex items-center gap-3 flex-1 min-w-0">
                                <FileAudio className="h-5 w-5 text-muted-foreground flex-shrink-0" />
                                <div className="flex-1 min-w-0">
                                    <p className="font-medium text-foreground truncate">
                                        {uploadData.file.name}
                                    </p>
                                    <p className="text-sm text-muted-foreground">
                                        {formatFileSize(uploadData.file.size)} •
                                        Ready for upload
                                    </p>
                                </div>
                            </div>
                            <div className="flex items-center gap-2 flex-shrink-0">
                                <Button
                                    variant="ghost"
                                    size="sm"
                                    onClick={handleEditFile}
                                    className="h-8 w-8 p-0"
                                >
                                    <Pencil className="h-4 w-4" />
                                </Button>
                                <Button
                                    variant="ghost"
                                    size="sm"
                                    onClick={handleDeleteFile}
                                    className="h-8 w-8 p-0 text-destructive hover:text-destructive"
                                >
                                    <Trash2 className="h-4 w-4" />
                                </Button>
                            </div>
                        </div>
                    </div>
                )}

                {/* Title */}
                <div className="space-y-2">
                    <div className="flex items-center justify-between">
                        <Label className="text-sm font-medium">
                            Title (required)
                        </Label>
                        <Button
                            variant="ghost"
                            size="sm"
                            onClick={handleEditTitle}
                            className="h-6 w-6 p-0"
                        >
                            <Pencil className="h-3 w-3" />
                        </Button>
                    </div>
                    <p className="text-foreground">
                        {uploadData.title || 'No title provided'}
                    </p>
                </div>

                {/* Description */}
                <div className="space-y-2">
                    <div className="flex items-center justify-between">
                        <Label className="text-sm font-medium">
                            Description (required)
                        </Label>
                        <Button
                            variant="ghost"
                            size="sm"
                            onClick={handleEditDescription}
                            className="h-6 w-6 p-0"
                        >
                            <Pencil className="h-3 w-3" />
                        </Button>
                    </div>
                    <p className="text-foreground text-sm line-clamp-3">
                        {uploadData.description || 'No description provided'}
                    </p>
                </div>

                {/* Link */}
                {uploadComplete && (
                    <div className="space-y-2">
                        <Label className="text-sm font-medium">Link</Label>
                        <div className="flex items-center gap-2">
                            <div className="flex-1 flex items-center gap-2 px-3 py-2 bg-muted rounded-md">
                                <LinkIcon className="h-4 w-4 text-muted-foreground flex-shrink-0" />
                                <span className="text-sm text-blue-600 truncate">
                                    {generateSermonLink()}
                                </span>
                            </div>
                            <Button
                                variant="ghost"
                                size="sm"
                                onClick={handleCopyLink}
                                className="h-8 w-8 p-0 flex-shrink-0"
                            >
                                <Copy className="h-4 w-4" />
                            </Button>
                        </div>
                        {linkCopied && (
                            <p className="text-xs text-green-600">
                                Link copied!
                            </p>
                        )}
                    </div>
                )}

                {/* Show More Button */}
                {!showMoreFields && (
                    <Button
                        type="button"
                        onClick={() => setShowMoreFields(true)}
                        className="bg-[#707070] cursor-pointer hover:bg-[#404040] text-[#EAEAEA] rounded-sm border-0"
                    >
                        <ChevronUp className="h-4 w-4 mr-2" />
                        Show more
                    </Button>
                )}
            </div>

            {/* Right Column - Thumbnail */}
            <div className="space-y-3 lg:sticky lg:top-0 lg:h-fit">
                <div className="space-y-2">
                    <div className="mb-2">
                        <Label>Thumbnail (required)</Label>
                        <div className="text-sm text-muted-foreground mb-2">
                            Set a thumbnail that stands out and draws viewers'
                            attention.
                        </div>
                    </div>

                    {uploadData.thumbnailPreview ? (
                        <div
                            className="relative w-full"
                            style={{ minHeight: '200px', aspectRatio: '4/3' }}
                        >
                            <div className="relative w-full h-full rounded-lg overflow-hidden border border-border/50">
                                <img
                                    src={uploadData.thumbnailPreview}
                                    alt="Sermon thumbnail"
                                    className="w-full h-full object-cover"
                                />

                                {/* Auto-generated Overlay */}
                                {isThumbnailAutoGenerated && (
                                    <div className="absolute bottom-2 left-2 flex items-center gap-1 rounded bg-background/90 px-2 py-1 text-xs font-medium text-foreground backdrop-blur-sm">
                                        <FileAudio className="h-3 w-3" />
                                        <span>Auto-generated</span>
                                    </div>
                                )}

                                {/* Edit Button */}
                                <Button
                                    variant="ghost"
                                    size="sm"
                                    onClick={handleEditThumbnail}
                                    className="absolute top-2 right-2 bg-background/80 backdrop-blur-sm hover:bg-background/90 h-8 w-8 p-0"
                                >
                                    <Pencil className="h-4 w-4" />
                                </Button>
                            </div>
                        </div>
                    ) : (
                        <div className="border-2 border-dashed rounded-lg p-8 text-center w-full min-h-[200px] flex items-center justify-center">
                            <p className="text-sm text-muted-foreground">
                                No thumbnail
                            </p>
                        </div>
                    )}
                </div>
            </div>

            {/* Action Buttons - These will be in the footer of the modal */}
            {/* Upload Status - This will be shown in the footer of the modal */}
        </div>
    );
};

export default ReviewSubmit;
