import { QueueItemSourceType } from './api-domain';
import { MediaSourceType, RepeatMode } from './playback.dto';

export interface CreateQueueItemDTO {
    mediaId: string;
    sourceType: MediaSourceType;
    sourceId: string;
    addedBy?: QueueItemSourceType;
}

export interface CreateQueueDTO {
    items: Array<CreateQueueItemDTO>;
    sourceType: MediaSourceType;
    sourceId: string;
    shuffle?: boolean;
    repeatMode?: RepeatMode;
    startIndex?: number;
}

export interface AddQueueItemDTO {
    mediaId: string;
    sourceType: MediaSourceType;
    sourceId: string;
    position?: number;
    addedBy?: QueueItemSourceType;
}

export interface RemoveQueueItemDTO {
    itemId: string;
}

export interface ReorderQueueDTO {
    itemId: string;
    newPosition: number;
}

export interface UpdateQueueDTO {
    currentIndex?: number;
    shuffle?: boolean;
    repeatMode?: RepeatMode;
}

export interface QueueItemResponseDTO {
    id: string;
    mediaId: string;
    sourceType: MediaSourceType;
    sourceId: string;
    position: number;
    addedAt: string;
    addedBy: QueueItemSourceType;
}

export interface QueueResponseDTO {
    id: string;
    code: string;
    items: QueueItemResponseDTO[];
    currentIndex: number;
    shuffle: boolean;
    repeatMode: RepeatMode;
    sourceType: MediaSourceType;
    sourceId: string;
    autoGenerated: boolean;
    locked: boolean;
    createdAt: string;
    updatedAt: string;
}
