import { MediaSourceType, RepeatMode } from '@/dtos/playback.dto';
import { QueueItemSourceType } from '@/dtos/api-domain';

export interface QueueItem {
    id: string;
    mediaId: string;
    sourceType: MediaSourceType;
    sourceId: string;
    position: number;
    addedAt: string;
    addedBy: QueueItemSourceType;
}

export interface Queue {
    id: string;
    code: string;
    items: QueueItem[];
    currentIndex: number;
    shuffle: boolean;
    repeatMode: RepeatMode;
    sourceType: MediaSourceType;
    sourceId: string;
    autoGenerated: boolean;
    locked: boolean;
    createdAt: string;
    updatedAt: string;
    listener?: unknown;
    _version?: number;
    _id?: string;
}

export default Queue;
